import Head from 'next/head'

const Header = () => {
    return(
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>Mesa de partes virtual</title>
            </Head>
        </>
    )
}

export default Header;